---
# tasks file for ./roles/security

# ------------------------------------------------------------------------------
- name: "AUDITD | install apt auditd"
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
    update_cache: true
  loop: "{{ security_auditd_dependencies | flatten(levels=1) }}"
  when: security_auditd_dependencies is defined
  tags:
    - security
    - auditd

# ------------------------------------------------------------------------------
- name: "AUDITD | config auditd conf"
  ansible.builtin.lineinfile:
    dest: "{{ security_auditd_config_directory }}/{{ security_auditd_config_file }}"
    regexp: '^(#(\s)*)?{{ item.key }}\s*=.*$'
    line: "{{ item.key }} = {{ item.value }}"
    state: present
    create: true
    owner: root
    group: root
    mode: "0640"
  loop: "{{ security_auditd_conf_variables | flatten(levels=1) }}"
  notify: Restart and enable auditd
  tags:
    - security
    - auditd

# ------------------------------------------------------------------------------
- name: "AUDITD | create rules.d directory"
  ansible.builtin.file:
    path: "{{ security_auditd_config_directory }}/rules.d"
    state: directory
    mode: "0750"
  notify: Restart and enable auditd
  tags:
    - security
    - auditd

- name: "AUDITD | config main rule (audit.rules)"
  ansible.builtin.template:
    src: audit.rules.j2
    dest: "{{ security_auditd_config_directory }}/rules.d/audit.rules"
    mode: "0600"
  notify: Restart and enable auditd
  tags:
    - security
    - auditd

# ------------------------------------------------------------------------------

- name: "AUDITD | config cron rule (audit.cron)"
  ansible.builtin.template:
    src: auditd.cron.j2
    dest: "/etc/cron.hourly/auditd"
    mode: "0755"
  notify: Restart and enable auditd
  when:
    - security_auditd_add_custom_cron_compressor | bool
  tags:
    - security
    - auditd
