---
# tasks file for ./roles/security

- name: FAIL2BAN | install dependencies
  ansible.builtin.apt:
    pkg: fail2ban
    state: present
    force_apt_get: true # apt-get instead of aptitude
    update_cache: true
  tags:
    - security
    - fail2ban

- name: FAIL2BAN | override jail.local configurations
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    backup: true
    owner: root
    group: root
    mode: "0640"
  tags:
    - security
    - fail2ban

- name: FAIL2BAN | add proxmox filder config
  ansible.builtin.template:
    src: proxmox.conf.j2
    dest: /etc/fail2ban/filder.d/proxmox.conf
    backup: true
    owner: root
    group: root
    mode: "0640"
  when:
    - security_fail2ban_proxmox is defined
    - security_fail2ban_proxmox | bool
  tags:
    - security
    - fail2ban

# ------------------------------------------------------------------------------
- name: FAIL2BAN | start and enable service
  ansible.builtin.service:
    name: fail2ban
    state: restarted
    enabled: true
  tags:
    - security
    - fail2ban
