---
# tasks file for ./roles/security

- name: Test vulnerability 1
  become: yes
  shell: ‘env x=‘’() { :;}; echo vulnerable’’ bash -c “echo this is a test”’
  executable: /bin/bash
  register: vulntest1
  failed_when: vulntest1.stdout | search(‘vulnerable')
  ignore_errors: yes
  changed_when: no

- name: Test vulnerability 2
  become: yes
  shell: ‘env X=‘’() { (a)=>’’ bash -c ‘’echo date’’;’
  executable: /bin/bash
  register: vulntest2
  failed_when: not vulntest2.stderr | search(‘error importing function definition’)
  ignore_errors: yes
  changed_when: no

- name: Cleanup after vulnerability test 2
  become: yes
  file:
  path: ~/echo
  state: absent
