---
# tasks file for ./roles/security

# AUDITD
- name: auditd
  become: true
  include: auditd.yml
  when: (security_setup_services is defined)
    and (security_setup_services.auditd is defined and security_setup_services.auditd | bool)
