---
# tasks file for ./roles/security

# AUDITD
- name: auditd
  become: true
  import_tasks: auditd.yml
  when:
    - security_setup_services is defined
    - security_setup_services.auditd is defined
    - security_setup_services.auditd | bool
  tags:
    - security
    - auditd

# FAIL2BAN
- name: fail2ban
  become: true
  import_tasks: fail2ban.yml
  when:
    - security_setup_services is defined
    - security_setup_services.fail2ban is defined
    - security_setup_services.fail2ban | bool
  tags:
    - security
    - fail2ban

# SNMP
- name: snmp
  import_tasks: snmp.yml
  when:
    - security_setup_services is defined
    - security_setup_services.snmp is defined
    - security_setup_services.snmp | bool
  tags:
    - security
    - snmp
