---
# tasks file for ./roles/security

# AUDITD
- name: "SECURITY | auditd"
  become: true
  ansible.builtin.import_tasks: auditd.yml
  when:
    - security_setup_services is defined
    - security_setup_services.auditd is defined
    - security_setup_services.auditd | bool
  tags:
    - security
    - auditd

# FAIL2BAN
- name: "SECURITY | fail2ban"
  become: true
  ansible.builtin.import_tasks: fail2ban.yml
  when:
    - security_setup_services is defined
    - security_setup_services.fail2ban is defined
    - security_setup_services.fail2ban | bool
  tags:
    - security
    - fail2ban

# SNMP
- name: "SECURITY | snmp"
  ansible.builtin.import_tasks: snmp.yml
  when:
    - security_setup_services is defined
    - security_setup_services.snmp is defined
    - security_setup_services.snmp | bool
  tags:
    - security
    - snmp

# SSH
- name: "SECURITY | config ssh - global"
  ansible.builtin.include_tasks: ssh.yml
  when:
    - security_setup_services is defined
    - security_setup_services.ssh is defined
    - security_setup_services.ssh | bool
    - security_ssh_only_client_setup is not defined or not security_ssh_only_client_setup | bool
  tags:
    - security
    - ssh

# SSH per user
- name: "SECURITY | config ssh - per user"
  ansible.builtin.include_tasks: ssh-user.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - security_setup_services is defined
    - security_setup_services.ssh is defined
    - security_setup_services.ssh | bool
  tags:
    - security
    - ssh
    - ssh-user
