---
# tasks file for ./roles/security
# set default secure permission, like described in "CIS Ubuntu Linux Benchmark => 6.1.*"

- name: set permission on multiple files for secure
  become: yes
  file:
    path: "{{ item.file }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - file: /etc/passwd
      owner: root
      group: root
      mode: '0644'
    - file: /etc/gshadow
      owner: root
      group: root
      mode: '0640'
    - file: /etc/shadow
      owner: root
      group: shadow
      mode: '0640'
    - file: /etc/group
      owner: root
      group: root
      mode: '0644'

    - file: /etc/passwd-
      owner: root
      group: root
      mode: '0600'
    - file: /etc/shadow-
      owner: root
      group: shadow
      mode: '0600'
    - file: /etc/group-
      owner: root
      group: root
      mode: '0644'
