---
# tasks file for ./roles/install_server

# ------------------------------------------------------------------------------
- name: "SNMP | install dependencies"
  become: true
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
    update_cache: true
  with_items:
    - "{{ security_snmp.snmp_packages }}"
    - "{{ security_snmp.snmp_additional_packages }}"
  tags:
    - security
    - snmp

# ------------------------------------------------------------------------------
- name: "SNMP | create snmp extension directory"
  become: true
  ansible.builtin.file:
    path: "{{ security_snmp_extension_scripts }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
    seuser: system_u
    serole: object_r
    setype: lib_t
    selevel: s0
  tags:
    - security
    - snmp

# ------------------------------------------------------------------------------
- name: "SNMP | install snmp extension"
  become: true
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: '{{ security_snmp_extension_scripts + "/" }}'
    owner: root
    group: root
    mode: "0755"
    seuser: system_u
    serole: object_r
    setype: lib_t
    selevel: s0
  with_items:
    - "{{ security_snmp.snmp_extension_list }}"
  tags:
    - security
    - snmp

# ------------------------------------------------------------------------------
- name: "SNMP | install snmp extension proxmox"
  become: true
  ansible.builtin.get_url:
    url: "{{ security_snmp.snmp_extension_proxmox.url }}"
    dest: '{{ security_snmp_extension_scripts + "/" }}'
    owner: root
    group: root
    mode: "0755"
    seuser: system_u
    serole: object_r
    setype: lib_t
    selevel: s0
  when: '"pve" in ansible_kernel'
  tags:
    - security
    - snmp

# ------------------------------------------------------------------------------
# - name: "SNMP | configure snmpd daemon"
#   become: true
#   ansible.builtin.template:
#     src: "default/snmpd.{{ ansible_os_family }}.j2"
#     dest: "{{ security_snmp.snmp_daemon_config }}"
#     owner: root
#     group: root
#     mode: 0644
#     seuser: system_u
#     serole: object_r
#     setype: etc_t
#     selevel: s0
#   notify:
#     - restart snmp
#   tags:
#     - security
#     - snmp

# ------------------------------------------------------------------------------
- name: "SNMP | check create snmp config"
  become: true
  ansible.builtin.template:
    src: "snmpd.conf.j2"
    dest: "{{ security_snmp.snmp_config }}"
    owner: root
    group: root
    mode: "0600"
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  register: check_snmp
  check_mode: true
  notify: restart and enable snmp
  tags:
    - security
    - snmp

# ------------------------------------------------------------------------------
- name: "SNMP | create snmp config"
  become: true
  ansible.builtin.template:
    src: "snmpd.conf.j2"
    dest: "{{ security_snmp.snmp_config }}"
    owner: root
    group: root
    mode: "0600"
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  when:
    - check_snmp is defined
    - check_snmp.changed | bool
  notify: restart and enable snmp
  tags:
    - security
    - snmp
