---
# handlers file for ./roles/security

# ------------------------------------------------------------------------------
- name: "AUDITD | restart and enable auditd"
  become: true
  ansible.builtin.systemd_service:
    name: auditd
    state: restarted
    enabled: true
    masked: false
  listen: "Restart and enable auditd"
  tags:
    - security
    - auditd

# ------------------------------------------------------------------------------
- name: "FAIL2BAN | restart and enable fail2ban"
  become: true
  ansible.builtin.systemd_service:
    name: fail2ban
    state: restarted
    enabled: true
    masked: false
  listen: "Restart and enable fail2ban"
  tags:
    - security
    - fail2ban

# ------------------------------------------------------------------------------
- name: "SNMP | restart and enable snmp"
  become: true
  ansible.builtin.systemd_service:
    name: "{{ security_snmp.snmp_service_name }}"
    state: restarted
    enabled: true
    masked: false
  listen: "Restart and enable snmp"
  tags:
    - security
    - snmp

# ------------------------------------------------------------------------------
- name: "SSH | restart and enable ssh"
  become: true
  ansible.builtin.systemd_service:
    name: ssh
    state: restarted
    enabled: "{{ security_ssh_service_enabled }}"
    masked: "{{ not security_ssh_service_enabled }}"
  listen: "Restart and enable ssh"
  tags:
    - security
    - ssh
