---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-security"
      include_role:
        name: "ansible-security"
  vars:
    security_setup_services:
      auditd: false
      fail2ban: true
      snmp: true
